### ISSUE TITLE
How to hide Volume popup ?

### ISSUE THREAD

**Issue by hitubansal123** [jpsim/JPSVolumeButtonHandler#20]
How to hide Volume popup ?

**Comment by jpsim** [comment]
It's tricky. In previous versions of iOS (years ago when I first wrote this), this code was sufficient to hide the HUD: https://github.com/jpsim/JPSVolumeButtonHandler/blob/4345cba6dd056dcbd84966c8689040a58735c6b3/JPSVolumeButtonHandler/JPSVolumeButtonHandler.m#L41-L47

Obviously that's very brittle code and no longer appears to work in recent versions of iOS. So this should be fixed by someone who's actually interested in that. I haven't used this component myself in years.

**Comment by hitubansal123** [comment]
So what you suggest .. Can you give me idea ?

**Comment by jpsim** [comment]
Debug the current brittle code to see how it could be adapted to work with recent iOS versions.
