### ISSUE TITLE
Outdated cocoapods

### ISSUE THREAD

**Issue by creitz** [jpsim/JPSVolumeButtonHandler#34]
The code in the repo doesn't appear to match the code in the cocoapod. Is it not the most recent version?

**Comment by jpsim** [comment]
There have been 11 commits since the last release: https://github.com/jpsim/JPSVolumeButtonHandler/compare/1.0.1...master

I don't actively use this project myself, so I rely on others to know if a release would actually be useful. I've just tagged [1.0.2](https://github.com/jpsim/JPSVolumeButtonHandler/releases/tag/1.0.2) and pushed it to CocoaPods trunk: https://github.com/CocoaPods/Specs/commit/ab068431202b15730e673b5a64fad29215eeed80

**Comment by creitz** [comment]
thanks!
